
# Under constructing. Doesn't works yet!

language: go

go:
  - "1.6.2"

before_install:
  - pushd $HOME
  - wget -q https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_linux_amd64-1.9.38.zip
  - unzip -q go_appengine_sdk_linux_amd64-1.9.38.zip
  - cd go_appengine
  - export GAE=$(pwd)
  - popd

install:
  - cd $TRAVIS_BUILD_DIR
  - export GOPATH=$TRAVIS_BUILD_DIR/vendor
  - export GOHOME=$GAE
  - export PATH=$GAE:$PATH
  - goapp env

  - echo $PATH
  - pwd
  
#  - go get github.com/PuerkitoBio/goquery

#script:
#  - cd dmm-eikaiwa-scheduler/src/github.com/tksmaru/dmm-eikaiwa-scheduler/app
#  - goapp test -cover -test.v=true